title: Quynh Vu # your name (or website title) here
logo: "/images/avatar.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  About me
  <br><br>
  I am Quynh Duc Vu, a student major in Computer Science (BS) at Seattle Pacific Univeristy(SPU). 
  I grew up playing video games, and they've changed my goal in life.
  <br><br>
  <a href="https://www.linkedin.com/in/quynh-vu-06a886187/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
